### ISSUE TITLE
Preprocess VOC dataset

### ISSUE THREAD

**Issue by Yangr116** [openseg-group/openseg.pytorch#95]
Hello, I have downloaded the VOC dataset and the context annotations. However, there is not a directory named "PytorchEncoding". 
Could you tell me what's the "PytorchEncoding/train.pth" and ""PytorchEncoding/val.pth" in pascal_context_generator.py ?
Thanks!

**Comment by Yangr116** [comment]
Done. ref:https://github.com/openseg-group/openseg.pytorch/blob/master/lib/datasets/preprocess/pascal_context/pascal_context_generator.sh

The "help" of the "--ori_root_dir" is wrong.  It should be "The directory of the **pascal voc 2010** data." instead of 'The directory of the **cityscapes** data.' (https://github.com/openseg-group/openseg.pytorch/blob/master/lib/datasets/preprocess/pascal_context/pascal_context_generator.py)

**Comment by Xuying2000** [comment]
I still don't quite understand what this means, can you tell me more about how to change it?
